SELECT SUM(TIV_2016) AS TIV_2016
FROM insurance 
WHERE PID NOT IN (SELECT PID FROM insurance a GROUP BY TIV_2015 HAVING COUNT(a.PID) = 1) AND 
PID IN (SELECT PID FROM insurance b GROUP BY LAT,LON HAVING COUNT(b.PID) = 1);